server:
  port: 8081
spring:
  application:
    name: shop-gateway
zuul:
  prefix: /api #请求前缀
  routes:
    item-service: /item/** #路由到商品微服务
    upload-service: /upload/** #路由到上传微服务
    search-service: /search/** #路由到搜索微服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    registry-fetch-interval-seconds: 5 #拉取服务间隔5s
#  server:
#    use-read-only-response-cache: false #关闭自我保护
