server:
  port: 8082

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.1.8
    port: 5672
    virtual-host: /shop
    username: shop
    password: shop
    template:
      exchange: SHOP.ITEM.EXCHANGE




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #设置心跳时间 续约更新时间间隔
    lease-expiration-duration-in-seconds: 15 #心跳过期时间 续约到期时间

mybatis:
  type-aliases-package: com.hjt.item.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


